# Generated by Django 2.0.4 on 2018-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('fixed_price', models.FloatField(null=True)),
                ('discounted_price', models.FloatField(null=True)),
                ('pic_name', models.URLField()),
                ('size', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
