# Generated by Django 2.0.4 on 2018-06-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('B', 'Best'), ('F', 'Featured'), ('N', 'Normal')], max_length=1)),
                ('subcategory', models.CharField(max_length=200)),
                ('category_3', models.CharField(max_length=200)),
                ('category_4', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('fixed_price', models.FloatField(null=True)),
                ('discounted_price', models.FloatField(null=True)),
                ('pic_name', models.CharField(max_length=300)),
                ('size', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['category', '-subcategory', '-category_3', '-category_4', 'name'],
            },
        ),
    ]
