# Generated by Django 2.0.4 on 2018-06-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180608_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='pic_name',
            field=models.CharField(max_length=300),
        ),
    ]
