# Generated by Django 2.0.4 on 2018-06-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180608_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('B', 'Best'), ('F', 'Featured'), ('N', 'Normal')], max_length=1)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('fixed_price', models.FloatField(null=True)),
                ('discounted_price', models.FloatField(null=True)),
                ('pic_name', models.CharField(max_length=300)),
                ('size', models.CharField(max_length=30)),
                ('subcategory', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['category', '-subcategory'],
            },
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
